### ISSUE TITLE
Pequeñas modificaciones al archivo de Client.cs, para que compilara en .Net 4.5, Visual Studio 2013 v12 update 5, 

### ISSUE THREAD

**Issue by icariantk** [compropago/sdk-cs-net#5]
namespace CompropagoSdk
{
    class Client
    {
        private static string VERSION = "2.0.2";

```
    private static string API_LIVE_URI = "http://api.compropago.com/v1/";
    private static string API_SANDBOX_URI = "http://api.compropago.com/v1/";

    private string publickey { get; set; }
    private string privatekey { get; set; }
    private bool live { get; set; }
    private string contained { get; set; }
    private string deployUri { get; set; }

    public Service api { get; set; }
```

**Comment by danteay** [comment]
Revise la compilación del código completo con Net Framework 4.5, 4.5.1 y 4.5.2 y no hay problema alguno con la estructura actual. Estaremos revisando la compativilidad de compilación en las versión de Visual Studio.

**Comment by icariantk** [comment]
![image](https://cloud.githubusercontent.com/assets/2768693/17182686/fbe8a578-53e9-11e6-8ee4-c1e427e90b85.png)

**Comment by danteay** [comment]
Se generaran los cambios correspondientes en las posteriores versiones.
